# Generated by Django 5.1.2 on 2024-11-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaso_app', '0002_teams_delete_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
