# Generated by Django 5.1.2 on 2024-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaso_app', '0004_coin_remove_team_a_team_team_id_team_team_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('turns', models.IntegerField(default=2)),
                ('answer', models.CharField(default='', max_length=100)),
                ('task_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='cost',
            field=models.IntegerField(default=2),
        ),
    ]
